import type { Actualite } from '@/types';

export const ACTUALITES: Actualite[] = [
  {
    id: 'actu-1',
    title: 'Nouvelle Promotion : -20% sur les Kits Solaires',
    excerpt: "Profitez d'une réduction exceptionnelle de 20% sur tous nos kits solaires résidentiels jusqu'à la fin du mois.",
    content: "Vicking Solar lance une promotion exceptionnelle sur l'ensemble de sa gamme de kits solaires résidentiels. Que vous souhaitiez équiper votre maison d'un système de 3kW ou de 10kW, bénéficiez de 20% de réduction sur le prix total de l'installation. Offre valable jusqu'au 31 juillet 2026.",
    date: '01/07/2026',
    image: '',
    category: 'promotion',
    featured: true,
  },
  {
    id: 'actu-2',
    title: 'Vicking Solar au Salon de l\'Énergie 2026',
    excerpt: "Venez nous rencontrer au Salon International de l'Énergie de Kinshasa du 15 au 18 juillet.",
    content: "Nous serons présents au Salon International de l'Énergie de Kinshasa pour vous présenter nos dernières innovations en matière d'énergie solaire. Découvrez nos nouveaux panneaux à haut rendement et nos solutions de stockage nouvelle génération. Entrée gratuite sur invitation.",
    date: '28/06/2026',
    image: '',
    category: 'evenement',
    featured: true,
  },
  {
    id: 'actu-3',
    title: 'Installation Record : 50kW en 48h',
    excerpt: "Nous avons réalisé l'installation d'un système hybride de 50kW pour un centre commercial à Gombe en un temps record.",
    content: "Notre équipe a relevé le défi d'installer un système hybride de 50kW avec batteries lithium pour un centre commercial du quartier Gombe à Kinshasa. L'installation complète, de la pose des panneaux à la mise en service, a été réalisée en seulement 48 heures. Une performance qui démontre notre expertise et notre efficacité.",
    date: '20/06/2026',
    image: '',
    category: 'realisation',
  },
  {
    id: 'actu-4',
    title: 'Nouveau Partenariat avec SolarTech',
    excerpt: "Vicking Solar signe un partenariat stratégique avec SolarTech pour distribuer exclusivement leurs panneaux nouvelle génération en RDC.",
    content: "Nous avons le plaisir d'annoncer notre partenariat exclusif avec SolarTech, fabricant mondial de panneaux solaires haut de gamme. Cette collaboration nous permet de vous offrir des panneaux monocristallins de dernière génération avec un rendement record de 24,5%. Disponibles dès maintenant dans notre showroom.",
    date: '15/06/2026',
    image: '',
    category: 'partenariat',
  },
  {
    id: 'actu-5',
    title: "Offre Spéciale : Kit Solaire + Batterie Offerts",
    excerpt: "Pour toute installation solaire de plus de 5kW, recevez une batterie de stockage lithium offerte d'une valeur de 1500$.",
    content: "Dans le cadre de notre programme 'Soleil pour Tous', nous offrons une batterie lithium de 5kWh pour toute installation solaire d'une puissance supérieure à 5kW. Une opportunité unique de bénéficier d'une autonomie énergétique totale à prix réduit. Offre limitée aux 50 premiers clients.",
    date: '10/06/2026',
    image: '',
    category: 'promotion',
  },
  {
    id: 'actu-6',
    title: "Témoignage : La Famille Mbemba passe au Solaire",
    excerpt: "Découvrez comment la famille Mbemba a réduit sa facture d'électricité de 80% grâce à notre installation solaire.",
    content: "La famille Mbemba, résidant à Ngaliema, a fait le choix du solaire avec Vicking Solar. Installés depuis 6 mois, leurs panneaux solaires de 8kW couvrent désormais 80% de leurs besoins énergétiques. 'Nous économisons près de 300$ par mois et nous n'avons plus de coupures', témoigne M. Mbemba.",
    date: '05/06/2026',
    image: '',
    category: 'temoinage',
  },
  {
    id: 'actu-7',
    title: 'Formation Gratuite : Tout savoir sur le Solaire',
    excerpt: "Inscrivez-vous à notre formation gratuite sur l'énergie solaire ouverte à tous les résidents de Kinshasa.",
    content: "Vicking Solar organise une formation gratuite d'une journée sur les bases de l'énergie solaire. Au programme : fonctionnement des panneaux, dimensionnement d'installation, entretien et maintenance. La formation aura lieu dans nos locaux à Kinshasa. Places limitées, inscription obligatoire.",
    date: '01/06/2026',
    image: '',
    category: 'formation',
  },
  {
    id: 'actu-8',
    title: 'Maintenance Gratuite pour nos Clients Fidèles',
    excerpt: "Dans le cadre de notre programme de fidélité, offrons une maintenance complète gratuite à tous nos clients de plus d'un an.",
    content: "Nous lançons notre programme de fidélité 'Client Premium'. Tous nos clients ayant installé leur système solaire depuis plus d'un an bénéficient d'une visite de maintenance gratuite incluant le nettoyage des panneaux, la vérification des onduleurs et un rapport de performance détaillé.",
    date: '25/05/2026',
    image: '',
    category: 'promotion',
  },
];
